[build]
command = "cd webapp/client && npm run build"
publish = "webapp/client/dist"
functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  # Reference secrets from UI:
  HF_TOKEN = "@hf_token"